# my global config
global:
  scrape_interval: %%scrape_interval%%s
  evaluation_interval: 15s 

remote_write:
  - url: '%%remote_write%%'

scrape_configs:
  - job_name: 'prometheus'
#    metrics_path: %%ingress_entry%%/metrics
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'home-assistant'
    metrics_path: /core/api/prometheus
    bearer_token: '%%token%%'
    static_configs:
    - targets: ['%%target%%']
      labels:
        latitude: '%%latitude%%'
        longitude: '%%longitude%%'
  - job_name: '%%additional_job_name%%'
    metrics_path: '/%%additional_metrics_path%%'
    static_configs:
      - targets: [%%additional_target%%]
